kumuluzee:
  name: user-service
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
    base-url: http://localhost:8080
  datasources:
    - jndi-name: jdbc/UserServiceDS
      connection-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/smartfitai_users
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:postgres}
      max-pool-size: 20

jwt:
  secret: Wq8U1MgZ9JTQUptfsNWtSuXxKen1Xqvl7TYQ1SwYou2pQnq/RtraU+Rn5OK+ZJVv
  expiration: 86400000 # 24 hours
  issuer: smartfit-ai
