kumuluzee:
  name: user-service
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: ${USER_SERVICE_PORT:8080}
    base-url: http://localhost:${USER_SERVICE_PORT:8080}
  datasources:
    - jndi-name: jdbc/UserServiceDS
      connection-url: jdbc:postgresql://${USER_DB_HOST:localhost}:${USER_DB_PORT:5432}/${USER_DB_NAME:smartfitai_users}
      username: ${USER_DB_USER:postgres}
      password: ${USER_DB_PASSWORD:postgres}
      max-pool-size: 20

jwt:
  secret: ${JWT_SECRET:Wq8U1MgZ9JTQUptfsNWtSuXxKen1Xqvl7TYQ1SwYou2pQnq/RtraU+Rn5OK+ZJVv}
  expiration: 86400000 # 24 hours
  issuer: ${JWT_ISSUER:smartfit-ai}
